Admins response
tatata05/kintai-backend pull request #4
Opened 2023-11-11 08:52 UTC by tatata05

admin 関連のレスポンス作成

2023-11-11 09:05 UTC, tatata05 commented
質問があります！

https://github.com/tatata05/kintai-backend/pull/4/files#diff-766c34fd6533171eaf54300c153f89d6002c35c02cfc9c5b219251f85180ad07:~:text=app/controllers/application_controller.rb

こちらの、エラー処理共通化が完成できておりません。

ActiveRecord::RecordNotFound など、ActiveRecordに存在しているエラー処理については、共通化することができました。
しかし、
- BadRequest
- Unauthorized
- Forbidden
これが ActiveRecord に存在せず、どう共通化すべきなのかわかりません...

「rails bad request error」
「rails forbidden 共通化」
「rails エラーハンドリング」
「rails エラー 共通化」
「devise 401 rescue」

など調べてみていますが、いまいち理解しきれず...
https://qiita.com/sibakenY/items/d86bc93417e718f11c2f
https://stackoverflow.com/questions/7297183/custom-devise-401-unauthorized-response
https://www.atotok.co.jp/labo/94e401f4af5552bf2fcd05693497d7cd

rails ガイドにも それっぽいものがあるもののこの処理もいまいち理解できていないです。
https://railsguides.jp/action_controller_overview.html#rescue

railse で特定のエラーを発生させて、その raise したエラーを rescue_from で処理するのかなとも思ったものの、
その場合は、結局は各アクションで if..else..end を使って条件分けをした上で、raise しないといけないのかなと思い意味がないのかなと...

理想としては、すでに 400 の badrequest などは起こるようになっているはずなので、
( 例えば、スクリーンショットのようなpatch アクションの時にbody に必要な情報が入っていないときなど )
<img width="1032" alt="スクリーンショット 2023-11-11 18 04 43" src="https://github.com/tatata05/kintai-backend/assets/123435331/8e906977-25cb-4c8b-ac6a-eba7542aa976">

こういった時の共通化はどうすべきなのでしょうか？？

2023-11-14 10:40 UTC, yuki-tachi0219 requested changes

2023-11-14 10:40 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +  end
〇〇.create! の処理が失敗したときにどんな種類のエラーが返ってくるかを見る。
それが`HogeHogeError`だとする
```
rescue HogeHogeError
  render_400(@absence.errors.full_messages)
end
```

2023-11-19 09:19 UTC, tatata05 commented
エラー共通化
https://github.com/tatata05/kintai-backend/pull/4/commits/3549e830bb244c50aed7c42b9cb438583ed124a1

忘れていたレスポンスの追加
https://github.com/tatata05/kintai-backend/pull/4/commits/6f203475a276983b3981cc7d3deb2c46d90a5889

auth関連のレスポンス修正
https://github.com/tatata05/kintai-backend/pull/4/commits/dd72aff6a921d293a177e202881acd0dd3b1314e

以上を行いました！！
ご確認お願いいたします。

2023-11-19 10:20 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
どんな議論したか忘れましたが、
```
rescue 〇〇Error
  render_400(message: "〇〇")
end
```
みたいな書き方にしたいって話をしてた気がします。

2023-11-20 13:04 UTC, tatata05 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
rescue BadRequest
で試してみたのですが、これだとそこでサーバーエラーになってしまいました...

ここでraise すれば、BadRequest のrender が呼び起こされて、記述が減るのでこれにしました！


スクリーンショットは、
```
rescue BadRequest
render ...
```
にしたときと
```
rescue
raise BadRequest
```
のレスポンスの違いです。
<img width="1040" alt="スクリーンショット 2023-11-20 22 03 07" src="https://github.com/tatata05/kintai-backend/assets/123435331/5dc62f00-12e2-4907-9773-cf776ff567ab">
<img width="1030" alt="スクリーンショット 2023-11-20 22 02 34" src="https://github.com/tatata05/kintai-backend/assets/123435331/47e72356-870c-4875-8b8f-00d403c60a19">

2023-11-21 04:29 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
この実験をする際、どのようにしてrescue節に処理をもっていったんですか？
- 18~25行あたりにraiseを入れた
- バリデーションエラーが出るように、paramsの値(statusなど)を変えた

どっちですか？
それによって解説が変わります。

2023-11-21 08:06 UTC, tatata05 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
@yuki-tachi0219 
エラーが起こるように、paramsに適切な値が入っていないようにしました！

2023-11-21 08:42 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
なるほど。バリデーションエラーがおきるように仕組んだということですね。
```
rescue => e
  binding.pry
  raise BadRequest
end
```
としてAPIリクエストをして、binding.pry内でeがどんなものになっているかを確認してください。
eが何のクラスのインスタンスなのかを確認し、そのクラスをコピって
```
  rescue 〇〇Error
    render_400(message: "〇〇")
  end
```
と実装してみましょうか

2023-11-21 09:06 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
```
rescue
  raise BadRequest
end
```
は、実践現場だとあまり使わないです。
BadRequest以外のヤバめのエラーが出たとしてもBadRequestエラーに勝手に変換されてしまい、
本来すぐに修正すべきトラブルが起きても気づけないという問題があるからです。

```
rescue
  raise 〇〇
end
```

という形にしなければいけないなら、ログにエラー内容を書き込んで開発者が定期的に見返す、というやり方が取られます。
ログ作るのは面倒なので、できれば特定のエラーだけをrescueでキャッチする形にしたいですね

2023-11-21 09:40 UTC, tatata05 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
@yuki-tachi0219 
ありがとうございます！

binding.pry で調べたところ、
`ActionController::ParameterMissing`
が該当のエラーでした。

考えてみたら、そもそもapplication_controller.rb で 上記エラー自体をrescue_from できていないのでは？
と思ったので、BadRequest ではなく直接的に
`rescue_from　ActionController::ParameterMissing .......`
としたところ、うまく拾えるようになりました！

また、この状態の時、
raise 〇〇
で別の例外 (NotFound等々) を発生させたところ、
その例外処理として それぞれのエラーメッセージを呼ぶことができていました！

これがその修正を行ったコミットです！
https://github.com/tatata05/kintai-backend/pull/4/commits/b47568efad26336e068bf7c84784215dafed3b48

2023-11-28 04:16 UTC, yuki-tachi0219 commented on app/controllers/api/v1/admin/absences_controller.rb
> +    raise BadRequest
OKです！いったんこの形にしましょうか。
これだと、ParameterMissingエラーの詳細(どのカラムに問題があるのか)が表示されない状態ですが、
フロントと繋ぎ合わせた際に問題が出たら直す感じでいきましょう。

2023-11-28 04:17 UTC, yuki-tachi0219 approved these changes
LGTM!

2023-12-01 12:37 UTC, merged